"""
PDF Report Generation Service
Generates professional PDF reports for various assessment types
"""

from io import BytesIO
from datetime import datetime
from typing import Optional, Dict, Any

from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor, black, white, grey
from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer,
    PageBreak,
    Image as RLImage,
)
from reportlab.lib import colors


class PDFService:
    """Service for generating professional PDF reports"""

    def __init__(self):
        """Initialize PDF service with styles"""
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()

    def _setup_custom_styles(self):
        """Setup custom paragraph styles for reports"""
        # Title style
        self.styles.add(
            ParagraphStyle(
                name="ReportTitle",
                parent=self.styles["Heading1"],
                fontSize=24,
                textColor=HexColor("#1e40af"),
                spaceAfter=30,
                alignment=1,  # Center
            )
        )

        # Section style
        self.styles.add(
            ParagraphStyle(
                name="SectionHeading",
                parent=self.styles["Heading2"],
                fontSize=14,
                textColor=HexColor("#1e40af"),
                spaceAfter=12,
                spaceBefore=12,
            )
        )

        # Normal text
        self.styles.add(
            ParagraphStyle(
                name="NormalText",
                parent=self.styles["Normal"],
                fontSize=11,
                leading=14,
                spaceAfter=6,
            )
        )

    def generate_diagnosis_report(
        self,
        patient_name: str,
        patient_id: str,
        diagnosis_data: Dict[str, Any],
        generated_by: str,
    ) -> bytes:
        """
        Generate a clinical diagnosis report PDF

        Args:
            patient_name: Patient's full name
            patient_id: Patient's UUID
            diagnosis_data: Diagnosis results including diagnosis type, confidence, recommendations
            generated_by: Doctor name or system that generated the report

        Returns:
            PDF file bytes
        """
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.5 * inch)
        story = []

        # Add header
        story.append(Paragraph("CLINICAL DIAGNOSIS REPORT", self.styles["ReportTitle"]))
        story.append(Spacer(1, 0.2 * inch))

        # Patient Information
        patient_info = [
            ["Patient Name:", patient_name],
            ["Patient ID:", patient_id],
            ["Generated By:", generated_by],
            ["Date:", datetime.now().strftime("%B %d, %Y")],
        ]

        patient_table = Table(patient_info, colWidths=[2 * inch, 4 * inch])
        patient_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (0, -1), HexColor("#e0e7ff")),
                    ("TEXTCOLOR", (0, 0), (-1, -1), black),
                    ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 10),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                    ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                ]
            )
        )
        story.append(patient_table)
        story.append(Spacer(1, 0.2 * inch))

        # Diagnosis Section
        story.append(Paragraph("PRIMARY DIAGNOSIS", self.styles["SectionHeading"]))
        diagnosis_type = diagnosis_data.get("diagnosis_type", "Not determined")
        confidence = diagnosis_data.get("confidence_score", 0)
        story.append(
            Paragraph(
                f"<b>Diagnosis:</b> {diagnosis_type}<br/><b>Confidence Score:</b> {confidence}%",
                self.styles["NormalText"],
            )
        )
        story.append(Spacer(1, 0.1 * inch))

        # Recommendations Section
        if diagnosis_data.get("recommendations"):
            story.append(Paragraph("RECOMMENDATIONS", self.styles["SectionHeading"]))
            for rec in diagnosis_data["recommendations"]:
                story.append(
                    Paragraph(f"• {rec}", self.styles["NormalText"])
                )
            story.append(Spacer(1, 0.1 * inch))

        # Clinical Notes
        if diagnosis_data.get("clinical_summary"):
            story.append(Paragraph("CLINICAL SUMMARY", self.styles["SectionHeading"]))
            story.append(
                Paragraph(diagnosis_data["clinical_summary"], self.styles["NormalText"])
            )

        # Add footer
        story.append(Spacer(1, 0.3 * inch))
        footer_text = f"Generated on {datetime.now().strftime('%B %d, %Y at %H:%M UTC')}"
        story.append(Paragraph(footer_text, self.styles["Normal"]))

        doc.build(story)
        return buffer.getvalue()

    def generate_treatment_plan_report(
        self,
        patient_name: str,
        patient_id: str,
        treatment_data: Dict[str, Any],
        generated_by: str,
    ) -> bytes:
        """
        Generate a treatment plan summary PDF

        Args:
            patient_name: Patient's full name
            patient_id: Patient's UUID
            treatment_data: Treatment plan including procedures, timeline, goals
            generated_by: Doctor name or system that generated the report

        Returns:
            PDF file bytes
        """
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.5 * inch)
        story = []

        # Add header
        story.append(Paragraph("TREATMENT PLAN", self.styles["ReportTitle"]))
        story.append(Spacer(1, 0.2 * inch))

        # Patient Information
        patient_info = [
            ["Patient Name:", patient_name],
            ["Patient ID:", patient_id],
            ["Treatment Planner:", generated_by],
            ["Date:", datetime.now().strftime("%B %d, %Y")],
        ]

        patient_table = Table(patient_info, colWidths=[2 * inch, 4 * inch])
        patient_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (0, -1), HexColor("#e0e7ff")),
                    ("TEXTCOLOR", (0, 0), (-1, -1), black),
                    ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 10),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                    ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                ]
            )
        )
        story.append(patient_table)
        story.append(Spacer(1, 0.2 * inch))

        # Treatment Goals
        story.append(Paragraph("TREATMENT GOALS", self.styles["SectionHeading"]))
        if treatment_data.get("goals"):
            for goal in treatment_data["goals"]:
                story.append(Paragraph(f"• {goal}", self.styles["NormalText"]))
        story.append(Spacer(1, 0.1 * inch))

        # Planned Procedures
        if treatment_data.get("procedures"):
            story.append(Paragraph("PLANNED PROCEDURES", self.styles["SectionHeading"]))
            procedures_data = []
            procedures_data.append(["Procedure", "Priority", "Status"])
            for proc in treatment_data["procedures"]:
                procedures_data.append(
                    [
                        proc.get("name", ""),
                        proc.get("priority", ""),
                        proc.get("status", "Pending"),
                    ]
                )

            proc_table = Table(procedures_data, colWidths=[3 * inch, 1.5 * inch, 1.5 * inch])
            proc_table.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), HexColor("#1e40af")),
                        ("TEXTCOLOR", (0, 0), (-1, 0), white),
                        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                        ("FONTSIZE", (0, 0), (-1, -1), 10),
                        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                        ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                    ]
                )
            )
            story.append(proc_table)
            story.append(Spacer(1, 0.1 * inch))

        # Treatment Timeline
        if treatment_data.get("timeline"):
            story.append(Paragraph("TREATMENT TIMELINE", self.styles["SectionHeading"]))
            story.append(
                Paragraph(treatment_data["timeline"], self.styles["NormalText"])
            )

        # Add footer
        story.append(Spacer(1, 0.3 * inch))
        footer_text = f"Generated on {datetime.now().strftime('%B %d, %Y at %H:%M UTC')}"
        story.append(Paragraph(footer_text, self.styles["Normal"]))

        doc.build(story)
        return buffer.getvalue()

    def generate_risk_assessment_report(
        self,
        patient_name: str,
        patient_id: str,
        risk_data: Dict[str, Any],
        generated_by: str,
    ) -> bytes:
        """
        Generate a risk assessment report PDF

        Args:
            patient_name: Patient's full name
            patient_id: Patient's UUID
            risk_data: Risk assessment including risk scores, factors, recommendations
            generated_by: Doctor name or system that generated the report

        Returns:
            PDF file bytes
        """
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.5 * inch)
        story = []

        # Add header
        story.append(Paragraph("RISK ASSESSMENT REPORT", self.styles["ReportTitle"]))
        story.append(Spacer(1, 0.2 * inch))

        # Patient Information
        patient_info = [
            ["Patient Name:", patient_name],
            ["Patient ID:", patient_id],
            ["Assessed By:", generated_by],
            ["Date:", datetime.now().strftime("%B %d, %Y")],
        ]

        patient_table = Table(patient_info, colWidths=[2 * inch, 4 * inch])
        patient_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (0, -1), HexColor("#e0e7ff")),
                    ("TEXTCOLOR", (0, 0), (-1, -1), black),
                    ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 10),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                    ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                ]
            )
        )
        story.append(patient_table)
        story.append(Spacer(1, 0.2 * inch))

        # Risk Summary
        story.append(Paragraph("RISK SUMMARY", self.styles["SectionHeading"]))
        overall_risk = risk_data.get("overall_risk_level", "Not assessed")
        risk_score = risk_data.get("risk_score", 0)
        story.append(
            Paragraph(
                f"<b>Overall Risk Level:</b> {overall_risk}<br/><b>Risk Score:</b> {risk_score}/100",
                self.styles["NormalText"],
            )
        )
        story.append(Spacer(1, 0.1 * inch))

        # Risk Factors
        if risk_data.get("risk_factors"):
            story.append(Paragraph("IDENTIFIED RISK FACTORS", self.styles["SectionHeading"]))
            for factor in risk_data["risk_factors"]:
                story.append(Paragraph(f"• {factor}", self.styles["NormalText"]))
            story.append(Spacer(1, 0.1 * inch))

        # Mitigation Strategies
        if risk_data.get("mitigation_strategies"):
            story.append(
                Paragraph("RECOMMENDED MITIGATION STRATEGIES", self.styles["SectionHeading"])
            )
            for strategy in risk_data["mitigation_strategies"]:
                story.append(Paragraph(f"• {strategy}", self.styles["NormalText"]))

        # Add footer
        story.append(Spacer(1, 0.3 * inch))
        footer_text = f"Generated on {datetime.now().strftime('%B %d, %Y at %H:%M UTC')}"
        story.append(Paragraph(footer_text, self.styles["Normal"]))

        doc.build(story)
        return buffer.getvalue()

    def generate_image_analysis_report(
        self,
        patient_name: str,
        patient_id: str,
        image_data: Dict[str, Any],
        generated_by: str,
    ) -> bytes:
        """
        Generate an image analysis report PDF

        Args:
            patient_name: Patient's full name
            patient_id: Patient's UUID
            image_data: Image analysis including findings, observations, recommendations
            generated_by: Radiologist or system that generated the report

        Returns:
            PDF file bytes
        """
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.5 * inch)
        story = []

        # Add header
        story.append(Paragraph("IMAGE ANALYSIS REPORT", self.styles["ReportTitle"]))
        story.append(Spacer(1, 0.2 * inch))

        # Patient Information
        patient_info = [
            ["Patient Name:", patient_name],
            ["Patient ID:", patient_id],
            ["Analyzed By:", generated_by],
            ["Date:", datetime.now().strftime("%B %d, %Y")],
        ]

        patient_table = Table(patient_info, colWidths=[2 * inch, 4 * inch])
        patient_table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (0, -1), HexColor("#e0e7ff")),
                    ("TEXTCOLOR", (0, 0), (-1, -1), black),
                    ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 10),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                    ("GRID", (0, 0), (-1, -1), 1, colors.grey),
                ]
            )
        )
        story.append(patient_table)
        story.append(Spacer(1, 0.2 * inch))

        # Image Details
        story.append(Paragraph("IMAGE DETAILS", self.styles["SectionHeading"]))
        image_type = image_data.get("image_type", "Not specified")
        tooth_number = image_data.get("tooth_number", "Not specified")
        story.append(
            Paragraph(
                f"<b>Image Type:</b> {image_type}<br/><b>Tooth Number:</b> {tooth_number}",
                self.styles["NormalText"],
            )
        )
        story.append(Spacer(1, 0.1 * inch))

        # Findings
        if image_data.get("findings"):
            story.append(Paragraph("KEY FINDINGS", self.styles["SectionHeading"]))
            story.append(
                Paragraph(image_data["findings"], self.styles["NormalText"])
            )
            story.append(Spacer(1, 0.1 * inch))

        # Clinical Observations
        if image_data.get("observations"):
            story.append(Paragraph("CLINICAL OBSERVATIONS", self.styles["SectionHeading"]))
            for obs in image_data["observations"]:
                story.append(Paragraph(f"• {obs}", self.styles["NormalText"]))

        # Add footer
        story.append(Spacer(1, 0.3 * inch))
        footer_text = f"Generated on {datetime.now().strftime('%B %d, %Y at %H:%M UTC')}"
        story.append(Paragraph(footer_text, self.styles["Normal"]))

        doc.build(story)
        return buffer.getvalue()
